require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-performance
  - rubocop-factory_bot

AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - bin/*
  NewCops: enable

Bundler/OrderedGems:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/environments/*.rb
    - config/routes.rb

Style/Documentation:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/SymbolArray:
  EnforcedStyle: brackets

Rails/I18nLocaleTexts:
  Enabled: false

Rails/Output:
  Exclude:
    - db/seeds.rb

Rails/SkipsModelValidations:
  Exclude:
    - db/seeds.rb

RSpec/DescribedClass:
  EnforcedStyle: explicit

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NotToNot:
  EnforcedStyle: to_not

FactoryBot/AssociationStyle:
  EnforcedStyle: explicit
