service: airport-gap
image: dennmart/airport-gap

servers:
  web:
    hosts:
      - 5.78.108.132
  worker:
    hosts:
      - 5.78.108.132
    cmd: bundle exec sidekiq -q default -q mailers

registry:
  server: ghcr.io
  username: dennmart
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    RAILS_ENV: production
    RACK_ENV: production
    RAILS_LOG_TO_STDOUT: true
    RAILS_SERVE_STATIC_FILES: true
    APPLICATION_HOST: 5.78.108.132
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL
    - REDIS_URL
    - SMTP_PASSWORD
    - SMTP_PORT
    - SMTP_SERVER
    - SMTP_USERNAME

builder:
  multiarch: false

accessories:
  db:
    image: postgres:16.2
    host: 5.78.108.132
    port: 10.0.1.1:5432:5432
    env:
      secret:
        - POSTGRES_DB
        - POSTGRES_USER
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
  redis:
    image: redis:7.2
    host: 5.78.108.132
    port: 10.0.1.1:6379:6379
    directories:
      - data:/data
